pref("extensions.zoteroautoexporting.filedeactivate", true);
pref("extensions.zoteroautoexporting.showdebug", false);
pref("extensions.zoteroautoexporting.fileinterval", 120);
pref("extensions.zoteroautoexporting.filetranslator", '9cb70025-a888-4a29-a210-93ec52da40d4');
pref("extensions.zoteroautoexporting.filepath", 'X:\\to\\folder\\test.bib');
pref("extensions.zoteroautoexporting.filenslfile", '');
pref("extensions.zoteroautoexporting.filestatus", 'No actions done');
pref("extensions.zoteroautoexporting.file-last", 0);
pref("extensions.zoteroautoexporting.file-bool-keep-interval", false);
pref("extensions.zoteroautoexporting.file-bool-collections-map", false);